name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - main # Trigger the workflow only on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (if you're using a build system)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies if you have any
      - name: Install dependencies
        run: npm install

      # Step 4: Fetch pinned repositories from GitHub GraphQL API
      - name: Fetch pinned projects from GitHub
        run: |
          curl -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
               -X POST -d '{"query": "query { user(login: \"ctkqiang\") { pinnedItems(first: 6, types: [REPOSITORY]) { nodes { ... on Repository { name description stargazerCount forkCount primaryLanguage { name } url } } } } }"}' \
               https://api.github.com/graphql \
               -o pinned_repos.json

      # Step 5: Update the index.html file with the fetched data
      - name: Update index.html with pinned repositories
        run: |
          # Parse the JSON file and insert the repository data into the index.html template
          node update-index.js pinned_repos.json index.html

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITHUB_DEPLOY_KEY }} # A deploy key for GitHub Pages
          publish_dir: ./ # Specify the directory to publish
